### ISSUE TITLE
Poor security via obscurity 

### ISSUE THREAD

**Issue by SwitchedOnScotland** [sven250/LoRa_two_step_authentication#1]
Disadvantages of two-factor authentication:

The device must be carried by the user, charged, and kept in range of a network whenever authentication might be necessary. 

If the device is unable to display messages, access is often impossible without backup plans.

The user must share their personal device number with the provider, reducing personal privacy and potentially allowing Spam/ DDOS.

Devices can be stolen, potentially allowing the thief to gain access into the user's accounts

For secure solutions hardware public key cryptography is required.
You cannot offer security via obscurity as designed in LoRaWAN. 
This is a well know subject in security.

For FREE solutions for all please read SwitchOnScotland.com on the issues of poor security offered with LoRaWAN v1.  

Session keys are not static.
Static AES keys are not secure.
LoRaWAN is broken as it stands.

Please do not use security in LoRaWAN v1 as it does not work.
All your AES keys have to be stored in a database, this can be hacked, copied and used by anyone.

With public key cryptography no SECRET keys are ever in the human domain, they are all secured inside a defended chip designed to do this type of security.
The company that designed this poor security for LoRaWAN just purchased a company called ATMEL for billions, these guys do security in chips. 

http://www.atmel.com/devices/ATECC508A.aspx

http://www.nytimes.com/2016/01/20/business/dealbook/microchip-technology-to-buy-atmel-for-nearly-3-6-billion.html?_r=0

Why would they design poor security and then purchase the answer to hide it!

Nice idea, just lacking security for IoT.

Please research security before giving solutions that fail the user.

**Comment by sven250** [comment]
First of all: This is a hobby project, you're not supposed to use it to secure valuable things. (such as your personal stock of plutonium) ;) [added this to readme file]
If you have additional features (like something to display messages?), I would love to see your pull request.
I don't know much about the security of LoRa, but it's obvious that it's less secure than communication with regular computers.
To prevent users from using this to protect important things, i added a readme file

--
Happy coding!
